$(document).ready(function() {
  /// Change between Celsius and Fahrenheit ///
  var degrees = "C";
  var celsius;
  var fahrenheit;
  document.getElementById("C").onclick = function() {
    if (!$(this).hasClass("active")) {
      switchDegrees();
    }
  };
  document.getElementById("F").onclick = function() {
    if (!$(this).hasClass("active")) {
      switchDegrees()
    }
  };

  function switchDegrees() {
    $("#degrees").find('a').toggleClass("active");
    degrees = $(".active").text().slice(1); // either C or F
    if (degrees == "C") {
      $("#temperature").html(celsius);
    } else if (degrees == "F") {
      $("#temperature").html(fahrenheit);
    }
  }

  /// Get GeoLocation ///
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(APIcall);
  } 

  function APIcall(position) {
    /// Info for API call ///
    var lon = position.coords.longitude;
    var lat = position.coords.latitude;
    var appid = "300a87cc5622df9bc25b4fbffe091943";
    var url = "http://api.openweathermap.org/data/2.5/forecast/weather?lat=" + lat + "&lon=" + lon + "&APPID=" + appid;
    /// API call ///
    $.getJSON(url, function(data) {
      /*$("#test").html(JSON.stringify(data));*/
      /// Display location ///
      var country = getCountryName(data.city.country)
      $("#location").html(data.city.name + ", " + country);
      /// Display temperature ///
      var temp = data.list[0].main.temp;
      celsius = Math.round(temp - 273.15);
      fahrenheit = Math.round(temp * (9 / 5) - 459.67);
      if (degrees == "C") {
        $("#temperature").html(celsius);
      } else if (degrees == "F") {
        $("#temperature").html(fahrenheit);
      }
      /// Display weather description ///
      var descr = data.list[0].weather[0].description;
      $("#description").html(descr);
      /// Display weather icon ///
      var weatherid = data.list[0].weather[0].id;
      /// day or night version ///
      var d = new Date();
      var t = d.getTime();
      var times = SunCalc.getTimes(new Date(),  position.coords.latitude,  position.coords.longitude); // uses a library from mourner on GitHub
      var sunriseT = times.sunrise.getTime();
      var sunsetT = times.sunset.getTime();
      if (d>sunriseT && d<sunsetT) {
        var url = weatherURLsDay[weatherid];
      } else {var url = weatherURLsNight[weatherid];}
      $(".icon").attr("src", url);
    });
  }
});

/// Weather ID to Icon URL Dictionary ///
/* Icons by Oxygen Icons, http://www.oxygen-icons.org and others, hosted on iconarchive.com */
var weatherURLsDay = {
  200: "icons/storm-day-icon.png",
  201: "icons/storm-day-icon.png",
  202: "icons/storm-icon.png",
  210: "icons/storm-day-icon.png",
  211: "icons/storm-icon.png",
  212: "icons/storm-icon.png",
  221: "icons/storm-icon.png",
  230: "icons/storm-day-icon.png",
  231: "icons/storm-day-icon.png",
  232: "icons/storm-day-icon.png",
  300: "icons/showers-scattered-day-icon.png",
  301: "icons/showers-scattered-day-icon.png",
  302: "icons/showers-scattered-icon.png",
  310: "icons/showers-scattered-day-icon.png",
  311: "icons/showers-scattered-day-icon.png",
  312: "icons/showers-scattered-icon.png",
  313: "icons/showers-scattered-icon.png",
  314: "icons/showers-day-icon.png",
  321: "icons/showers-scattered-icon.png",
  500: "icons/showers-scattered-day-icon.png",
  501: "icons/showers-day-icon.png",
  502: "icons/showers-icon.png",
  503: "icons/showers-icon.png",
  504: "icons/showers-icon.png",
  511: "icons/freezing-rain-icon.png",
  520: "icons/showers-scattered-day-icon.png",
  521: "icons/showers-scattered-icon.png",
  522: "icons/showers-icon.png",
  531: "icons/showers-icon.png",
  600: "icons/snow-scattered-day-icon.png",
  601: "icons/snow-icon.png",
  602: "icons/snow-icon.png",
  611: "icons/sleet-icon.png",
  612: "icons/sleet-icon.png",
  615: "icons/snow-rain-icon.png",
  616: "icons/snow-rain-icon.png",
  620: "icons/snow-scattered-day-icon.png",
  621: "icons/snow-scattered-icon.png",
  622: "icons/snow-icon.png",
  701: "icons/fog-icon.png",
  711: "icons/fog-icon.png",
  721: "icons/fog-icon.png",
  731: "icons/dust-icon.png",
  741: "icons/fog-icon.png",
  751: "icons/dust-icon.png",
  761: "icons/dust-icon.png",
  762: "icons/dust-icon.png",
  771: "icons/storm-icon.png",
  781: "icons/tornado-icon.png",
  800: "clear-icon.png",
  801: "icons/few-clouds-icon.png",
  802: "icons/clouds-icon.png",
  803: "icons/clouds-icon.png",
  804: "icons/many-clouds-icon.png",
  900: "icons/tornado-icon.png",
  901: "icons/storm-icon.png",
  902: "icons/storm-icon.png",
  903: "icons/snow-flake-icon.png",
  904: "icons/clear-icon.png",
  905: "icons/wind-breeze-icon.png",
  906: "icons/hail-icon.png",
  951: "icons/clear-icon.png",
  952: "icons/wind-breeze-icon.png",
  953: "icons/wind-breeze-icon.png",
  954: "icons/wind-breeze-icon.png",
  955: "icons/wind-breeze-icon.png",
  956: "icons/wind-breeze-icon.png",
  957: "icons/wind-breeze-icon.png",
  958: "icons/wind-breeze-icon.png",
  959: "icons/wind-breeze-icon.png",
  960: "icons/storm-icon.png",
  961: "icons/storm-icon.png",
  962: "icons/storm-icon.png",
}
var weatherURLsNight = {
  200: "icons/storm-night-icon.png",
  201: "icons/storm-night-icon.png",
  202: "icons/storm-icon.png",
  210: "icons/storm-night-icon.png",
  211: "icons/storm-icon.png",
  212: "icons/storm-icon.png",
  221: "icons/storm-icon.png",
  230: "icons/storm-night-icon.png",
  231: "icons/storm-night-icon.png",
  232: "icons/storm-night-icon.png",
  300: "icons/showers-scattered-night-icon.png",
  301: "icons/showers-scattered-night-icon.png",
  302: "icons/showers-scattered-icon.png",
  310: "icons/showers-scattered-night-icon.png",
  311: "icons/showers-scattered-night-icon.png",
  312: "icons/showers-scattered-icon.png",
  313: "icons/showers-scattered-icon.png",
  314: "icons/showers-night-icon.png",
  321: "icons/showers-scattered-icon.png",
  500: "icons/showers-scattered-night-icon.png",
  501: "icons/showers-night-icon.png",
  502: "icons/showers-icon.png",
  503: "icons/showers-icon.png",
  504: "icons/showers-icon.png",
  511: "icons/freezing-rain-icon.png",
  520: "icons/showers-scattered-night-icon.png",
  521: "icons/showers-scattered-icon.png",
  522: "icons/showers-icon.png",
  531: "icons/showers-icon.png",
  600: "icons/snow-scattered-night-icon.png",
  601: "icons/snow-icon.png",
  602: "icons/snow-icon.png",
  611: "icons/sleet-icon.png",
  612: "icons/sleet-icon.png",
  615: "icons/snow-rain-icon.png",
  616: "icons/snow-rain-icon.png",
  620: "icons/snow-scattered-night-icon.png",
  621: "icons/snow-scattered-icon.png",
  622: "icons/snow-icon.png",
  701: "icons/fog-icon.png",
  711: "icons/fog-icon.png",
  721: "icons/fog-icon.png",
  731: "icons/dust-icon.png",
  741: "icons/fog-icon.png",
  751: "icons/dust-icon.png",
  761: "icons/dust-icon.png",
  762: "icons/dust-icon.png",
  771: "icons/storm-icon.png",
  781: "icons/tornado-icon.png",
  800: "icons/clear-night-icon.png",
  801: "icons/few-clouds-night-icon.png",
  802: "icons/clouds-night-icon.png",
  803: "icons/clouds-night-icon.png",
  804: "icons/many-clouds-icon.png",
  900: "icons/tornado-icon.png",
  901: "icons/storm-icon.png",
  902: "icons/storm-icon.png",
  903: "icons/snow-flake-icon.png",
  904: "icons/clear-night-icon.png",
  905: "icons/wind-breeze-icon.png",
  906: "icons/hail-icon.png",
  951: "icons/clear-night-icon.png",
  952: "icons/wind-breeze-icon.png",
  953: "icons/wind-breeze-icon.png",
  954: "icons/wind-breeze-icon.png",
  955: "icons/wind-breeze-icon.png",
  956: "icons/wind-breeze-icon.png",
  957: "icons/wind-breeze-icon.png",
  958: "icons/wind-breeze-icon.png",
  959: "icons/wind-breeze-icon.png",
  960: "icons/storm-icon.png",
  961: "icons/storm-icon.png",
  962: "icons/storm-icon.png",
}

/// Country Code to Country Name Converter ///
var isoCountries = {
  'AF': 'Afghanistan',
  'AX': 'Aland Islands',
  'AL': 'Albania',
  'DZ': 'Algeria',
  'AS': 'American Samoa',
  'AD': 'Andorra',
  'AO': 'Angola',
  'AI': 'Anguilla',
  'AQ': 'Antarctica',
  'AG': 'Antigua And Barbuda',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AW': 'Aruba',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BS': 'Bahamas',
  'BH': 'Bahrain',
  'BD': 'Bangladesh',
  'BB': 'Barbados',
  'BY': 'Belarus',
  'BE': 'Belgium',
  'BZ': 'Belize',
  'BJ': 'Benin',
  'BM': 'Bermuda',
  'BT': 'Bhutan',
  'BO': 'Bolivia',
  'BA': 'Bosnia And Herzegovina',
  'BW': 'Botswana',
  'BV': 'Bouvet Island',
  'BR': 'Brazil',
  'IO': 'British Indian Ocean Territory',
  'BN': 'Brunei Darussalam',
  'BG': 'Bulgaria',
  'BF': 'Burkina Faso',
  'BI': 'Burundi',
  'KH': 'Cambodia',
  'CM': 'Cameroon',
  'CA': 'Canada',
  'CV': 'Cape Verde',
  'KY': 'Cayman Islands',
  'CF': 'Central African Republic',
  'TD': 'Chad',
  'CL': 'Chile',
  'CN': 'China',
  'CX': 'Christmas Island',
  'CC': 'Cocos (Keeling) Islands',
  'CO': 'Colombia',
  'KM': 'Comoros',
  'CG': 'Congo',
  'CD': 'Congo, Democratic Republic',
  'CK': 'Cook Islands',
  'CR': 'Costa Rica',
  'CI': 'Cote D\'Ivoire',
  'HR': 'Croatia',
  'CU': 'Cuba',
  'CY': 'Cyprus',
  'CZ': 'Czech Republic',
  'DK': 'Denmark',
  'DJ': 'Djibouti',
  'DM': 'Dominica',
  'DO': 'Dominican Republic',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'SV': 'El Salvador',
  'GQ': 'Equatorial Guinea',
  'ER': 'Eritrea',
  'EE': 'Estonia',
  'ET': 'Ethiopia',
  'FK': 'Falkland Islands (Malvinas)',
  'FO': 'Faroe Islands',
  'FJ': 'Fiji',
  'FI': 'Finland',
  'FR': 'France',
  'GF': 'French Guiana',
  'PF': 'French Polynesia',
  'TF': 'French Southern Territories',
  'GA': 'Gabon',
  'GM': 'Gambia',
  'GE': 'Georgia',
  'DE': 'Germany',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GR': 'Greece',
  'GL': 'Greenland',
  'GD': 'Grenada',
  'GP': 'Guadeloupe',
  'GU': 'Guam',
  'GT': 'Guatemala',
  'GG': 'Guernsey',
  'GN': 'Guinea',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HT': 'Haiti',
  'HM': 'Heard Island & Mcdonald Islands',
  'VA': 'Holy See (Vatican City State)',
  'HN': 'Honduras',
  'HK': 'Hong Kong',
  'HU': 'Hungary',
  'IS': 'Iceland',
  'IN': 'India',
  'ID': 'Indonesia',
  'IR': 'Iran, Islamic Republic Of',
  'IQ': 'Iraq',
  'IE': 'Ireland',
  'IM': 'Isle Of Man',
  'IL': 'Israel',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JP': 'Japan',
  'JE': 'Jersey',
  'JO': 'Jordan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KI': 'Kiribati',
  'KR': 'Korea',
  'KW': 'Kuwait',
  'KG': 'Kyrgyzstan',
  'LA': 'Lao People\'s Democratic Republic',
  'LV': 'Latvia',
  'LB': 'Lebanon',
  'LS': 'Lesotho',
  'LR': 'Liberia',
  'LY': 'Libyan Arab Jamahiriya',
  'LI': 'Liechtenstein',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'MO': 'Macao',
  'MK': 'Macedonia',
  'MG': 'Madagascar',
  'MW': 'Malawi',
  'MY': 'Malaysia',
  'MV': 'Maldives',
  'ML': 'Mali',
  'MT': 'Malta',
  'MH': 'Marshall Islands',
  'MQ': 'Martinique',
  'MR': 'Mauritania',
  'MU': 'Mauritius',
  'YT': 'Mayotte',
  'MX': 'Mexico',
  'FM': 'Micronesia, Federated States Of',
  'MD': 'Moldova',
  'MC': 'Monaco',
  'MN': 'Mongolia',
  'ME': 'Montenegro',
  'MS': 'Montserrat',
  'MA': 'Morocco',
  'MZ': 'Mozambique',
  'MM': 'Myanmar',
  'NA': 'Namibia',
  'NR': 'Nauru',
  'NP': 'Nepal',
  'NL': 'Netherlands',
  'AN': 'Netherlands Antilles',
  'NC': 'New Caledonia',
  'NZ': 'New Zealand',
  'NI': 'Nicaragua',
  'NE': 'Niger',
  'NG': 'Nigeria',
  'NU': 'Niue',
  'NF': 'Norfolk Island',
  'MP': 'Northern Mariana Islands',
  'NO': 'Norway',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PW': 'Palau',
  'PS': 'Palestinian Territory, Occupied',
  'PA': 'Panama',
  'PG': 'Papua New Guinea',
  'PY': 'Paraguay',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PN': 'Pitcairn',
  'PL': 'Poland',
  'PT': 'Portugal',
  'PR': 'Puerto Rico',
  'QA': 'Qatar',
  'RE': 'Reunion',
  'RO': 'Romania',
  'RU': 'Russian Federation',
  'RW': 'Rwanda',
  'BL': 'Saint Barthelemy',
  'SH': 'Saint Helena',
  'KN': 'Saint Kitts And Nevis',
  'LC': 'Saint Lucia',
  'MF': 'Saint Martin',
  'PM': 'Saint Pierre And Miquelon',
  'VC': 'Saint Vincent And Grenadines',
  'WS': 'Samoa',
  'SM': 'San Marino',
  'ST': 'Sao Tome And Principe',
  'SA': 'Saudi Arabia',
  'SN': 'Senegal',
  'RS': 'Serbia',
  'SC': 'Seychelles',
  'SL': 'Sierra Leone',
  'SG': 'Singapore',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'SB': 'Solomon Islands',
  'SO': 'Somalia',
  'ZA': 'South Africa',
  'GS': 'South Georgia And Sandwich Isl.',
  'ES': 'Spain',
  'LK': 'Sri Lanka',
  'SD': 'Sudan',
  'SR': 'Suriname',
  'SJ': 'Svalbard And Jan Mayen',
  'SZ': 'Swaziland',
  'SE': 'Sweden',
  'CH': 'Switzerland',
  'SY': 'Syrian Arab Republic',
  'TW': 'Taiwan',
  'TJ': 'Tajikistan',
  'TZ': 'Tanzania',
  'TH': 'Thailand',
  'TL': 'Timor-Leste',
  'TG': 'Togo',
  'TK': 'Tokelau',
  'TO': 'Tonga',
  'TT': 'Trinidad And Tobago',
  'TN': 'Tunisia',
  'TR': 'Turkey',
  'TM': 'Turkmenistan',
  'TC': 'Turks And Caicos Islands',
  'TV': 'Tuvalu',
  'UG': 'Uganda',
  'UA': 'Ukraine',
  'AE': 'United Arab Emirates',
  'GB': 'United Kingdom',
  'US': 'United States',
  'UM': 'United States Outlying Islands',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VU': 'Vanuatu',
  'VE': 'Venezuela',
  'VN': 'Viet Nam',
  'VG': 'Virgin Islands, British',
  'VI': 'Virgin Islands, U.S.',
  'WF': 'Wallis And Futuna',
  'EH': 'Western Sahara',
  'YE': 'Yemen',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe'
};

function getCountryName(countryCode) {
  if (isoCountries.hasOwnProperty(countryCode)) {
    return isoCountries[countryCode];
  } else {
    return countryCode;
  }
}